name: Release

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run tsc
        run: yarn tsc

      - name: Run lint
        run: yarn eslint .

      - name: Run test
        run: yarn test
