name: CI on PR

on:
  pull_request:
    branches:
      - main
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: yarn

      - name: Run tsc
        run: yarn tsc

      - name: Run lint
        run: yarn eslint .

      - name: Run test
        run: yarn test

      - name: Run build
        run: yarn build
